apiVersion: v1
kind: Config
preferences: {}
current-context: default
clusters:
- cluster:
    server: https://MASTER_IP:6443
    certificate-authority: /root/data/ca.crt
  name: default
contexts:
- context:
    cluster: default
    user: admin
  name: default
users:
- name: admin
  user:
    client-certificate: /root/data/kubecfg.crt
    client-key: /root/data/kubecfg.key
